.github/workflows/codacy.yml, .github/workflows/codeql.yml, .github/workflows/flawfinder.yml
Create security workflows for scanning the code and finding security issues.
The added workflows are:
* codacy
* codeql
* flawfinder
=> Add security workflows to the CI/CD pipeline

.github/workflows/clang_format.yml, src/Agent.hpp, src/Graph.hpp, src/Itinerary.hpp, src/utility/HashFunctions.hpp
* Create clang-format workflow
* Formatting
=> Create clang-format workflow (#10)

src/Agent.hpp
This is the first step for closing issue #3.
=> Add `velocity` and (travel) `time` attributes

src/Street.hpp, test/Street/Test_street.cpp
=> added `density()` and `maxSpeed`

src/Graph.hpp, src/Street.hpp, test/Graph/Test_graph.cpp
Add a constructor for building Graphs from the adjacency matrix, passed as a SparseMatrix (issue #19)
=> Add constructor for building Graph from adjacency matrix

src/Agent.hpp, src/Itinerary.hpp, src/Street.hpp, test/Itinerary/Test_itinerary.cpp, test/Street/Test_street.cpp
=> Move transition matrices from `Agent` to `Itinerary`

src/Agent.hpp, src/Graph.hpp, src/Itinerary.hpp, src/Node.hpp, src/Street.hpp
Reorder the definition of class attributes in order to improve the memory efficiency (issue #33).
=> Improve memory management of data structure classes

.github/workflows/clang_format.yml, .github/workflows/codeql.yml
=> Fix C++ build command in `codeql.yml`

src/dsm/headers/Graph.hpp, test/Graph/Test_graph.cpp
=> Autogenerate graph from `importAdj`

.github/workflows/benchmark.yml
Create workflow for automatic execution of benchmarks.
=> Create workflow for benchmarks

src/dsm/headers/Graph.hpp, src/dsm/headers/SparseMatrix.hpp, test/Test_sparsematrix.cpp
Moreover, fix a bug in the `reshape` function
=> Add `insert_and_expand` function to SparseMatrix

src/dsm/headers/Agent.hpp, src/dsm/headers/Graph.hpp, src/dsm/headers/Itinerary.hpp, src/dsm/headers/SparseMatrix.hpp, src/dsm/headers/Street.hpp
=> Feature enhance exceptions

src/dsm/headers/Graph.hpp, src/dsm/headers/SparseMatrix.hpp, src/dsm/utility/DijkstraResult.hpp, test/Test_graph.cpp
This PR:
* implements the Dijkstra algorithm for finding the shortest paths between any pair of nodes (issue #6)
* adds `emptyRow` and `emptyColumn` methods for `SparseMatrix`, which erase all the elements in a row/col (set the elements to zero) while mantaining the shape of the matrix
=> Implement Dijkstra algorithm

benchmark/Graph/BenchGraph.cpp, benchmark/Street/BenchStreet.cpp, src/dsm/headers/Graph.hpp, src/dsm/headers/Node.hpp, src/dsm/headers/Street.hpp, src/dsm/utility/TypeTraits/is_node.hpp, test/Test_is_node.cpp, test/Test_node.cpp, test/Test_street.cpp
In order to implement the dynamics, here some feature of the node are enhanced.
In particular:
- added a capacity, i.e. the max number of agents a node can handle (by default is always one, otherwise node would be dead)
- added `enqueue` and `dequeue` methods
- added `isFull` method to check if the node is at its max capacity.
=> Add queue managemnet in Node class

benchmark/Street/BenchStreet.cpp, src/dsm/headers/Agent.hpp, src/dsm/headers/Itinerary.hpp, test/Test_agent.cpp, test/Test_itinerary.cpp, test/Test_street.cpp
now it's an Id type parameter, will be usefull in dynamics
=> Reworked Itinerary Id

src/dsm/headers/Agent.hpp, src/dsm/headers/Street.hpp, test/Test_agent.cpp
To uniform Agent to other classes
=> Changed `index` into `id`

src/dsm/dsm.hpp
Remove old import of hash functions in `dsm.hpp`
=> Remove import of `HashFunction`

src/dsm/headers/SparseMatrix.hpp, test/Test_sparsematrix.cpp
=> Add optional parameter to getRow and getCol functions

src/dsm/headers/Street.hpp, test/Test_street.cpp
=> Add Angle parameter

.github/workflows/profile_exec_time.yml, .github/workflows/profile_mem_usage.yml, .gitignore, profiling/CMakeLists.txt, profiling/main.cpp, profiling/parse_massif.cpp
This PR:
* creates a workflow that profiles the execution of a simulation with `gprof`
* creates a workflow that analyzes the heap usage of the simulation as a function of the machine instructions, using `massif` (which is part of `valgrind`). Subsequently the peak and integral of the graph are calculated
=> Add profiling of execution and memory usage

src/dsm/headers/Agent.hpp
=> Add definition of `Agent::resetTime`

CMakeLists.txt, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Street.hpp, test/CMakeLists.txt, test/Test_street.cpp
- [Add Street::nAgents() function](https://github.com/sbaldu/DynamicalSystemFramework/commit/c6e8d444fb76b4e9a5c9cfb8fc050d4630e49005)
- [Add Street::isFull() and rework Street::density()](https://github.com/sbaldu/DynamicalSystemFramework/commit/3857a2f720b1f83d9bb6d3b4ea9d497eb63ef97a)
=> Correct density and flow measurement units

CMakeLists.txt, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Street.hpp, test/CMakeLists.txt, test/Test_dynamics.cpp, test/Test_street.cpp
- Add `Dynamics::meanSpireInputFlow()` and `Dynamics::meanSpireOutputFlow()`
- [Rename SpireStreet::input/outputFlow() in Counts()](https://github.com/sbaldu/DynamicalSystemFramework/commit/1130d230d534abdee0230e18e8c45e69fb836b9f)
- [Rename measurement error into std](https://github.com/sbaldu/DynamicalSystemFramework/commit/3c3fbfa705909f9b78b3288e807f2b1617d4a1f1)
=> Add `Dynamics::meanSpireInputFlow()` and `Dynamics::meanSpireOutputFlow()`

CMakeLists.txt, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Street.hpp, test/CMakeLists.txt
- Add `Dynamics::optimizeTrafficLights` function
- Add `Street::normDensity` getter
=> Add `Dynamics::optimizeTrafficLights` function

CMakeLists.txt, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Node.hpp, test/CMakeLists.txt, test/Test_dynamics.cpp
- Enhance turn mapping
- Fix traffic lights optimization algorithm
- Minor changes
=> Enhance turn counts and minor fixes

src/dsm/headers/Agent.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Graph.hpp, src/dsm/headers/Itinerary.hpp, src/dsm/headers/Node.hpp, src/dsm/headers/SparseMatrix.hpp, src/dsm/headers/Street.hpp, src/dsm/utility/DijkstraResult.hpp, src/dsm/utility/Logger.hpp, src/dsm/utility/TypeTraits/is_agent.hpp, src/dsm/utility/TypeTraits/is_itinerary.hpp, src/dsm/utility/TypeTraits/is_node.hpp, src/dsm/utility/TypeTraits/is_numeric.hpp, src/dsm/utility/TypeTraits/is_street.hpp, src/dsm/utility/queue.hpp
Substitute include guards with `#pragma once` for simplicity
=> Substitute include guards with `pragma once`

.github/workflows/cmake_examples.yml, examples/slow_charge_rb.cpp, examples/slow_charge_tl.cpp, examples/stalingrado.cpp, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Graph.hpp, test/Test_dynamics.cpp
=> Add Graph max capacity

.github/workflows/benchmark.yml, .github/workflows/clang_format.yml, .github/workflows/cmake_install.yml, .github/workflows/cmake_test.yml, .github/workflows/codacy.yml, .github/workflows/codeql.yml, .github/workflows/flawfinder.yml, .github/workflows/gh-pages.yml, .github/workflows/profile_exec_time.yml, .github/workflows/profile_mem_usage.yml, .github/workflows/pylint.yml, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Graph.hpp, src/dsm/headers/Itinerary.hpp, src/dsm/headers/Node.hpp, src/dsm/headers/SparseMatrix.hpp, src/dsm/headers/Street.hpp, src/dsm/utility/Logger.hpp
=> Replace strings concatenation with std::format

.gitignore, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, test/CMakeLists.txt, utils/plotter.py
- Close #94
Divided the work for the given itineraries among several threads.
=> Optimize `updatePaths` function

LICENSE
=> Move to `CC-BY-NC-SA-4.0` license

src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, test/Test_dynamics.cpp
=> Add `addAgentsRandomly` function to Dynamic class

src/dsm/headers/Graph.hpp, src/dsm/headers/Street.hpp
=> Feature add street n lanes

examples/slow_charge_rb.cpp, examples/slow_charge_tl.cpp, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, test/Test_dynamics.cpp
=> Add `setDestinationNodes` function to Dynamics class

src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, test/Test_dynamics.cpp
Improve the calculation of data average and standard deviation by optimizing the cache use.
By looping over the array one time, elements are accumulated in the mean and std. dev. values inside the same cache load.
=> Improve the statistic measurement class

.github/workflows/cmake_install.yml, .github/workflows/cmake_install_macos.yml, CMakeLists.txt, README.md
Update the installation of the library after merge of #209.
=> Update installation cmake file

Doxyfile, benchmark/Adj/BenchAdj.cpp, benchmark/Adj/CMakeLists.txt, benchmark/CMakeLists.txt, benchmark/Dynamics/BenchDynamics.cpp, examples/slow_charge_rb.cpp, examples/slow_charge_tl.cpp, examples/stalingrado.cpp, profiling/main.cpp, src/dsm/dsm.hpp, src/dsm/headers/AdjacencyMatrix.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Graph.hpp, src/dsm/headers/Itinerary.hpp, src/dsm/headers/RoadDynamics.hpp, src/dsm/sources/AdjacencyMatrix.cpp, src/dsm/sources/Graph.cpp, src/dsm/sources/Itinerary.cpp, test/Test_AdjacencyMatrix.cpp, test/Test_dynamics.cpp, test/Test_graph.cpp
- Close #254 
- Update to v2.4.0
- `SparseMatrix` is now deprecated
=> Implement new adjacency

src/dsm/dsm.hpp, src/dsm/headers/Street.hpp, src/dsm/sources/Street.cpp, test/Test_street.cpp, test/data/nodes.csv
=> Add `setLaneMapping` function to Street class

webapp/index.html, webapp/script.js, webapp/styles.css
=> Improve `webapp`
