src/Agent.hpp, src/Graph.hpp, src/Itinerary.hpp, src/Node.hpp, src/SparseMatrix.hpp, src/Street.hpp, src/utility/TypeTraits.hpp, test/Test_sparsematrix.cpp
* Define `is_numeric_v` type traits, which check that a template paramenter is either an integral or a floating point type (Note: we can't use `std::is_arithmetic` because it inlcudes `bool` and `char`, which are unfit to be indexes of a matrix)
* Add constaints on all the template parameters using `type_traits` and C++20 `requires`
* Fix missing includes in `TypeTraits.hpp`
* Fix index types in tests of `SparseMatrix`
* Remove unneeded tests of `SparseMatrix`
=> Add contraints for the template parameters

src/Itinerary.hpp, src/Street.hpp, src/utility/TypeTraits.hpp, test/Street/Test_street.cpp
This PR updates the `Street` class, adding some missing core methods (issue #21).
* add `setNodePair` methods
* add constructor accepting a nodePair
* remove useless constructor taking the size parameter
* add `enqueue` and `dequeue` methods for the Street's `queue` member
* add tests for all the constructors, overloads of `setNodePair` and `enqueue`/`dequeue` methods
=> Feature street missing methods

src/Graph.hpp, src/utility/TypeTraits/is_node.hpp, src/utility/TypeTraits/is_street.hpp
This PR:
* adds specialization of the `is_node` and `is_street` type traits for const refs of said types
* uses forwarding references in the variadic methods of the `Graph` class, `addNodes` and `addStreets` (issue #37)
=> Use forwarding references in `Graph::addNodes` and `Graph::addStreets`

src/dsm/headers/Agent.hpp
I noticed a typo in the return types of the `Agent` class getters. This fixes it
=> Fix typo in Agent getters return type

src/dsm/headers/Agent.hpp, src/dsm/headers/Street.hpp, test/Street/Test_street.cpp
This PR implements some major changes to the structure of the `Agent` class:
* add `Size` template parameter for the size of the street occupied by the Agent
* remove the `m_previousPosition` data member because it is mostly useless
* rename the `m_position` data member as `m_streetId`
* add `Delay` template parameter and `m_delay` data member, representing the spatial or temporal distance between the agent and the one in front of it
=> Rework of `Agent` class

benchmark/Graph/CMakeLists.txt, benchmark/Street/CMakeLists.txt
In the last reworks of the structure of the library we forgot to update the benchmarks as well. This PR fixes this.
=> Update include paths in benchmark cmake files

src/dsm/headers/Graph.hpp
When converting `Graph` members from sets to maps we forgot to update the insertion of nodes with the `addNode` methods. This PR fixes this.
This is also needed for PR #67, because it causes the compilation of benchmarks to fail.
=> Fix insertion of nodes with `addNode`

src/dsm/headers/Graph.hpp, src/dsm/headers/Street.hpp, test/Test_graph.cpp, test/Test_street.cpp
* This PR modifies the `addStreet` methods so that, in addition to inserting the street in the street map, they also insert its nodes in the node map (issue #64).
* In order to implement the previous node it became necessary to modify the constructors of the `Street` class so that they all require the pair of nodes (otherwise I could insert a street without nodes, and when trying to insert them in the node map this would cause problems)
* Some new checks have been added to the tests of the `Graph` class to make sure that the bug is now fixed
=> Add nodes to nodeSet when using `addStreet`

src/dsm/headers/Street.hpp, src/dsm/utility/queue.hpp
This PR creates two types of queues, `dsm::queue` and `dsm::priority_queue`, which inherit from the stl implementation and add iterators and access operators. This is done because in the evolution of the system we need to be able to iterate over the elements of the queues (issue #101).
The iterators are defined through the iterators of the `Container` members of the two base classes, which are protected.
Note: I didn't update the queue member of the `Node` classes because we are reworking it in PR #96.
=> Feature iteration over queues

src/dsm/headers/Dynamics.hpp, test/Test_dynamics.cpp
Rewrite `mean...()` functions to return an object of type `Measurement` containing mean and standard deviation.
Links #108
Closes #109
=> Add error on observable mean measurements

CMakeLists.txt, profiling/main.cpp, src/dsm/headers/Agent.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Itinerary.hpp, src/dsm/headers/SparseMatrix.hpp, test/Test_agent.cpp, test/Test_dynamics.cpp, test/Test_itinerary.cpp
- Now an itinerary is uniquely defined by its destination. No more duplicates are needed
- Adjusted the code to the new itineraries
- Update version
**N.B.**: I won't identify the itinerary by its destination because it could be usefull to have many paths to the same destination but different weights, e.g. updating them with `updatePaths()`. This will cover #88 and #94.
=> Rework itinerary

CMakeLists.txt, src/dsm/headers/Node.hpp, test/Test_node.cpp
In this PR:
- Improve `setDelay` function for traffic light nodes: now it can change dynamically during the evolution.
- Fix #140
=> Dynamic `setDelay` function in nodes

.dockerignore, Dockerfile
This PR creates a dockerfile which allows to test, benchmark and profile the library in a docker container based on `almalinux 9`.
In the `/app` folder inside the container there is a folder `test` where the content of the project is copied for testing purposes, and another folder named `develop` which is empty and is where the host folder should be mounter for developing inside the container.
=> Create dockerfile for testing and developing

src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Node.cpp, src/dsm/headers/Node.hpp, src/dsm/headers/Street.cpp, src/dsm/headers/Street.hpp, test/Test_dynamics.cpp
The base idea is adding a new `std::pair<double, double>`  to Traffic Light class.
In this way, we can have four different time intervals:
- `0` -> `delay.first * (1 - pair.first)` in which is green for right/straight turns;
- `delay.first * (1 - pair.first)` -> `delay.first` in which is green for left turns;
- `delay.first` -> `delay.first + delay.second * (1 - pair.second)` in which is red for right/straight turns;
- `delay.first + delay.second * (1 - pair.second)` -> `delay.second` in which is red for left turns;
=> Manage multi-lane Traffic Lights

benchmark/Dynamics/BenchDynamics.cpp, examples/Makefile, examples/slow_charge_rb.cpp, examples/slow_charge_tl.cpp, examples/stalingrado.cpp, profiling/main.cpp, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/FirstOrderDynamics.cpp, src/dsm/headers/FirstOrderDynamics.hpp, src/dsm/headers/RoadDynamics.hpp, test/Test_dynamics.cpp, utils/plotter.py
- Template Dynamics on `agent_t` agent type
- Template RoadDynamics on `delay_t` delay type
- Remove template from FirstOrderDynamics: it uses Typedef's `Delay`
=> Enhance templates in Dynamics classes

examples/slow_charge_rb.cpp, examples/stalingrado.cpp, src/dsm/dsm.hpp, src/dsm/headers/Agent.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/Graph.cpp, src/dsm/headers/Graph.hpp, src/dsm/headers/RoadDynamics.hpp, test/Test_agent.cpp, test/Test_dynamics.cpp
- (Finally) close #107
Random agents are immortal agents. The only way to kill them is to set the passage probability at junctions: if a normal agent cannot pass, it waits, but if a random agent cannot pass, it dies.
=> Add random agents management

examples/slow_charge_tl.cpp, src/dsm/dsm.hpp, src/dsm/headers/Dynamics.hpp, src/dsm/headers/RoadDynamics.hpp, src/dsm/headers/TrafficLight.cpp, src/dsm/headers/TrafficLight.hpp, test/Test_dynamics.cpp
New features:
- now algorithms consider exit queues instead of street density
- queues are weighted basing on the number of lanes
- bugfixes
=> Enhance traffic lights optimization algorithm

utils/get_osm_data.py
New features:
- Now filtering is done using `osmnx` features rather than my buggy filters :c
- Intersection are now merged within a default radius of 20 meters (can be changed passing it as arg)
- Duplicated edges are discarded by default to prevent conflict. If discarded, a temporary plot will be promped showing them in red
- Script produces two files, i.e. the complete network and the network resulting from all filtering processes
=> Update `get_osm_data` script

src/dsm/dsm.hpp, src/dsm/headers/AdjacencyMatrix.hpp, src/dsm/sources/AdjacencyMatrix.cpp, test/Test_AdjacencyMatrix.cpp
Deifne a new AdjacencyMatrix class that implements a sparse matrix in CSR format (issue #254).
=> Define new class for Adjacency matrix

src/dsm/dsm.hpp, src/dsm/headers/RoadDynamics.hpp, src/dsm/headers/RoadNetwork.hpp, src/dsm/sources/RoadNetwork.cpp, src/dsm/sources/Street.cpp, test/Test_graph.cpp
=> Add `autoMapStreetLanes` function to RoadNetwork class
